module.exports = {
  PING: "neuroagi:ping",
  START_REPORT_COLLECTION: "neuroagi:start-report-collection",
  SUBMIT_QUESTIONNAIRE: "neuroagi:submit-questionnaire",
  GOTO_LABORATORY: "neuroagi:goto-laboratory",
  SUBMIT_LABORATORY: "neuroagi:submit-laboratory",
  GOTO_PRE_DOCTOR_ROOM: "neuroagi:goto-pre-doctor-room",
  SUBMIT_PRE_DOCTOR_ROOM: "neuroagi:submit-pre-doctor-room",
  START_DOCTOR: "neuroagi:start-doctor",
  DOCTOR_STREAM_DELTA: "neuroagi:doctor-stream-delta",
  DOCTOR_STREAM_REASONING_DELTA: "neuroagi:doctor-stream-reasoning-delta",
  DOCTOR_STREAM_DONE: "neuroagi:doctor-stream-done",
  DOCTOR_STREAM_ERROR: "neuroagi:doctor-stream-error",
  GET_USAGE_TOTALS: "neuroagi:get-usage-totals",
  USAGE_UPDATE: "neuroagi:usage-update",
  OPEN_DEV_TOOLS: "neuroagi:open-dev-tools",
  GET_MODELS_CONFIG: "neuroagi:get-models-config",
  UPDATE_MODELS_CONFIG: "neuroagi:update-models-config",
};
