module.exports = {
  PING: "neuroagi:ping",
  GET_USAGE_TOTALS: "neuroagi:get-usage-totals",
  RESET_USAGE_TOTALS: "neuroagi:reset-usage-totals",
  USAGE_UPDATE: "neuroagi:usage-update",
  OPEN_DEV_TOOLS: "neuroagi:open-dev-tools",
  GET_CREDENTIALS: "neuroagi:get-credentials",
  UPDATE_CREDENTIALS: "neuroagi:update-credentials",
  OPEN_EXTERNAL_URL: "neuroagi:open-external-url",
  TEST_OPENROUTER_KEY: "neuroagi:test-openrouter-key",
  TEST_TAVILY_KEY: "neuroagi:test-tavily-key",
  GET_MODELS_CONFIG: "neuroagi:get-models-config",
  UPDATE_MODELS_CONFIG: "neuroagi:update-models-config",
  BENCHMARK_MODELS: "neuroagi:benchmark-models",
  BENCHMARK_PROGRESS: "neuroagi:benchmark-progress",
  GET_LOGS: "neuroagi:get-logs",
  CLEAR_LOGS: "neuroagi:clear-logs",
  LOG_UPDATE: "neuroagi:log-update",
  ADVANCE_SEND: "neuroagi:advance-send",
  ADVANCE_PROGRESS: "neuroagi:advance-progress",
  ADVANCE_CANCEL: "neuroagi:advance-cancel",
};
